spring.main.banner-mode=off
spring.jmx.enabled=false
spring.threads.virtual.enabled=true
spring.mvc.servlet.load-on-startup=1
logging.level.root=WARN
server.port=${PORT:8080}
server.address=${HOST:0.0.0.0}
server.server-header=
server.error.whitelabel.enabled=false
server.tomcat.max-connections=65536
server.tomcat.accept-count=8192
server.tomcat.keep-alive-timeout=60s
server.tomcat.max-keep-alive-requests=-1
server.tomcat.mbeanregistry.enabled=false
